name: webservices
channels:
  - conda-forge
platforms:
  - linux-64
dependencies:
  - python =3.11
  - git
  - conda-smithy >=3.22.0
  - conda-forge-tick >=2024.9.26
  - conda-build
  - conda-forge-feedstock-ops >=0.3.0
  - pip
  - setuptools
  - setuptools_scm
  - tini
  - pygithub
  - requests
  - gitpython
  - pyyaml
  - pytest
