name: base
channels:
- conda-forge
dependencies:
 - git
 - conda-smithy>=3.22.0
 - conda-forge-pinning
 - conda-build
 - pip
 - setuptools
 - setuptools_scm
 - tini
 - pygithub
 - requests
 - gitpython
 - pyyaml
