name: container

on:
  workflow_dispatch: null
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

jobs:
  container:
    name: push container
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: login to docker hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: condaforgebot
          password: ${{ secrets.CF_BOT_DH_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v5
        with:
          push: true
          tags: condaforge/webservices-dispatch-action:prod

      - name: push README to docker hub
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # v1
        env:
          DOCKER_USER: condaforgebot
          DOCKER_PASS: ${{ secrets.CF_BOT_DH_PASSWORD }}
        with:
          destination_container_repo: condaforge/webservices-dispatch-action:prod
          provider: dockerhub
          short_description: "conda-forge image used to power the admin webservices GitHub Actions integrations"
          readme_file: "Dockerfile_README.md"
