name: docker-push

on:
  push:
    branches:
      - main
  schedule:
     - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC

jobs:
  docker-push:
    name: docker-push
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: condaforgebot
          password: ${{ DH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: condaforge/webservices-dispatch-action:prod
