name: keep-alive
on:
  schedule:
    - cron: "0 6 * * SUN" # Once weekly on Sunday @ 0600 UTC
permissions:
  contents: write

jobs:
  keep-alive:
    name: Alive
    if: github.repository == 'conda-forge/webservices-dispatch-action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: gautamkrishnar/keepalive-workflow@beb86212524e1ae856d1cd80efb44e73bf7daf4a # 2.0.1
        with:
          time_elapsed: 50 # days
