name: keep-alive
on:
  schedule:
    - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC
permissions:
  contents: write

jobs:
  keep-alive:
    name: Alive
    if: github.repository == 'conda-forge/webservices-dispatch-action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@14b7c72e9af14bddbbc1022a6f0bd20b1eac2619
        with:
          commit_message: "Ah ah ah, stayin' alive"
          committer_username: conda-forge-bot
          committer_email: "conda-forge-bot@users.noreply.github.com"
          time_elapsed: 50  # days
