name: tests

on:
  push:
    branches:
      - main
  pull_request: null
  schedule:
     - cron: "0 6 * * SUN"  # Once weekly on Sunday @ 0600 UTC
  workflow_dispatch: null

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda info -a

          mamba install \
              git \
              python="3.10" \
              pip \
              tini \
              pygithub \
              gitpython \
              requests \
              flake8 \
              pytest \
              conda-smithy \
              conda-forge-pinning \
              conda-build

          pip install --no-deps -e .

      - name: lint and run tests
        shell: bash -l {0}
        run: |
          flake8 webservices_dispatch_action
          pytest -vv webservices_dispatch_action
          command -v run-webservices-dispatch-action

      # - name: build the docker image
      #   shell: bash -l {0}
      #   run: |
      #     docker build -t test .
      #
      - name: generate token
        id: generate_token
        uses: conda-forge/github-app-token@e3ab451d57e120b956292a1fa1d21fe4ba171c36
        with:
          app_id: ${{ secrets.CF_CURATOR_APP_ID }}
          private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

      - name: run live rerender tests
        shell: bash -l {0}
        run: |
          echo "${DH_PASSWORD}" | docker login -u condaforgebot --password-stdin
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python tests/run_live_rerender_test.py --build-and-push
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}

      - name: run live version update tests
        shell: bash -l {0}
        run: |
          echo "${DH_PASSWORD}" | docker login -u condaforgebot --password-stdin
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python tests/run_live_version_update_test.py
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}

      - name: run live version update tests w/ user version
        shell: bash -l {0}
        run: |
          echo "${DH_PASSWORD}" | docker login -u condaforgebot --password-stdin
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python tests/run_live_version_update_test.py --version=0.14
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}

  docker-push:
    name: docker-push
    runs-on: "ubuntu-latest"
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: condaforgebot
          password: ${{ secrets.DH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: condaforge/webservices-dispatch-action:prod

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: condaforgebot
          DOCKER_PASS: ${{ secrets.DH_PASSWORD }}
        with:
          destination_container_repo: condaforge/webservices-dispatch-action:prod
          provider: dockerhub
          short_description: "conda-forge image used to power the admin webservices GitHub Actions integrations"
          readme_file: "Dockerfile_README.md"
