name: tests

on:
  push:
    branches:
      - main
  pull_request: null
  schedule:
    - cron: "0 6 * * SUN" # Once weekly on Sunday @ 0600 UTC
  workflow_dispatch: null

concurrency:
  group: ${{ github.workflow }}

jobs:
  tests:
    name: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca # v3
        with:
          python-version: "3.11"
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          miniforge-version: latest
          miniforge-variant: Mambaforge
          environment-file: environment.yml

      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda info -a
          mamba install --yes pytest flake8
          pip install --no-deps -e .

      - name: lint and run tests
        shell: bash -l {0}
        run: |
          flake8 webservices_dispatch_action
          pytest -vv webservices_dispatch_action
          command -v run-webservices-dispatch-action

      - name: generate token
        id: generate_token
        uses: actions/create-github-app-token@a0de6af83968303c8c955486bf9739a57d23c7f1 # v1
        with:
          app-id: ${{ secrets.CF_CURATOR_APP_ID }}
          private-key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: run live rerender tests
        shell: bash -l {0}
        run: |
          echo "${DH_PASSWORD}" | docker login -u condaforgebot --password-stdin
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python tests/run_live_rerender_test.py --build-and-push
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DH_PASSWORD: ${{ secrets.CF_BOT_DH_PASSWORD }}

      - name: run live version update tests
        shell: bash -l {0}
        run: |
          echo "${DH_PASSWORD}" | docker login -u condaforgebot --password-stdin
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python tests/run_live_version_update_test.py
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DH_PASSWORD: ${{ secrets.CF_BOT_DH_PASSWORD }}

      - name: run live version update tests w/ user version
        shell: bash -l {0}
        run: |
          echo "${DH_PASSWORD}" | docker login -u condaforgebot --password-stdin
          git config --global user.name "conda-forge-admin"
          git config --global user.email "pelson.pub+conda-forge@gmail.com"
          git config --global pull.rebase false
          python tests/run_live_version_update_test.py --version=0.14
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          DH_PASSWORD: ${{ secrets.CF_BOT_DH_PASSWORD }}

  docker-push:
    name: docker-push
    runs-on: "ubuntu-latest"
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3

      - name: Login to Docker Hub
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3
        with:
          username: condaforgebot
          password: ${{ secrets.CF_BOT_DH_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5
        with:
          push: true
          tags: condaforge/webservices-dispatch-action:prod

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # v1
        env:
          DOCKER_USER: condaforgebot
          DOCKER_PASS: ${{ secrets.CF_BOT_DH_PASSWORD }}
        with:
          destination_container_repo: condaforge/webservices-dispatch-action:prod
          provider: dockerhub
          short_description: "conda-forge image used to power the admin webservices GitHub Actions integrations"
          readme_file: "Dockerfile_README.md"

  keepalive-job:
    name: Keep alive
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: gautamkrishnar/keepalive-workflow@beb86212524e1ae856d1cd80efb44e73bf7daf4a # 2.0.1
